'user stric'

var mongoose = require('mongoose');

var Schema = mongoose.Schema;
/*
Here we need one model UrlShorten with following fields,

originalUrl- URL used to perform the shortening service.
shortUrl- Unique short code generated by using short-id
urlCode- The Unique code created in shortUrl.
createdAt- Created date
updatedAt -updated date
*/
var urlShortenSchema = Schema({
  originalUrl: String,
  shortUrl: String,
  urlCode: String,
  createdAt: {type: Date, default: Date.now()},
  updatedAt: {type: Date, default: Date.now()}
});

module.exports = mongoose.model('urlShorten', urlShortenSchema);